# apiVersion: v1
# kind: Service
# metadata:
#   name: reddit-service
# spec:
#   type: NodePort
#   selector:
#     app: reddit
#   ports:
#   - protocol: TCP
#     port: 80
#     targetPort: 8000
#     nodePort: 30080  # Optional: specify or let K8s assign one
apiVersion: v1
kind: Service
metadata:
  name: reddit-service
spec:
  type: LoadBalancer
  selector:
    app: reddit
  ports:
    - protocol: TCP
      port: 8080       # External port
      targetPort: 8000  # Matches containerPort


